= Marcus Chen - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: INVESTIGAPPTOR

---

== Overview

Investigapptor is a desktop application used for investigators to manage cases as simple, straightforward and efficient as possible.

The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Added the Investigator package, which is a subclass of the person class
** What it does: Allows Investigapptor to store a new type of person in the address book that is can handle and more methods and data for Investigator.

** Justification: This enhancement is required as the person package is insufficient to perform the task required. As I wanted to accommodate future enhance of more types of people, the person class was used as a superclass to store the
basic information rather than just morphing the person class.
** Highlights: This enhancement has includes much changes to the model component of the Investigapptor allowing it to apply the same general commands to all subclass of the Person class while still being able to use specfic command for specific classes.
The Investigator also stores a live reference to all his cases that works with undo/redo feature by the usage of hashcode to always ensure it reference the correct case.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*:
** Implemented Backup command:
+
Allows user to create and name a backup of the current state of the investigapptor.
** Implemented ListInvestigatorCases command:
+
Allows user to view all cases allocated to the selected investigator.
** Implemented GUI for Investigator Details:
+
Created a html file to display the investigator details in a clear and more presentable format.
** Refactor the following command in order for investigator to integrate properly into Invesstigapptor.
+
*** AddInvestigatorCommand
*** EditInvestigatorCommand
*** DeleteInvestigatorCommand
** Implemented CrimeCaseBuilder class
+
CrimeCaseBuilder used in JUnit testing to help build CrimeCase
** Implemented InvestigatorBuilder class
+
InvestigatorBuilder used in JUnit testing to help build CrimeCase
* *Code contributed*: [https://github.com/CS2103JAN2018-F14-B3/main/blob/master/collated/functional/Marcus-cxc.md[Functional code]] [https://github.com/CS2103JAN2018-F14-B3/main/blob/master/collated/test/Marcus-cxc.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` (1 releases) on GitHub
** Documentation:
*** Did screenshots for several commands in the User Guide: https://github.com/CS2103JAN2018-F14-B3/main/pull/255[#255] https://github.com/CS2103JAN2018-F14-B3/main/pull/260[#260]
*** Did the navigating the interface section for the User Guide: https://github.com/CS2103JAN2018-F14-B3/main/pull/231[#231]
*** Filled in the future enhancement in the user doc: https://github.com/CS2103JAN2018-F14-B3/main/pull/244[#244]
*** Update the Design component for the Developer Guide https://github.com/CS2103JAN2018-F14-B3/main/pull/255[#255]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addinv]
include::../UserGuide.adoc[tag=editinv]
include::../UserGuide.adoc[tag=deleteinv]
include::../UserGuide.adoc[tag=listinvcase]
include::../UserGuide.adoc[tag=Backup]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=investigator]


include::../DeveloperGuide.adoc[tag=backup]



== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
