= Marcus Chen - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: INVESTIGAPPTOR

---

== Overview

Investigapptor is a desktop application used for investigators to manage cases as simple, straightforward and efficient as possible.

The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Added the Investigator package, which is a subclass of the person class
** What it does: Allows Investigapptor to store a new type of person in the address book that is can handle and more methods and data for Investigator.

** Justification: This enhancement is required as the person package is insufficient to perform the task required. As I wanted to accommodate future enhance of more types of people, the person class was used as a superclass to store the
basic information rather than just morphing the person class.
** Highlights: This enhancement has includes much changes to all major changes to all components of the Invesitgapptor,
especially the model component to allow the Investigator to stores a live reference to all his cases that works with undo/redo feature by the usage of hashcode.


* *Minor enhancement*:
** Implemented Backup command:
+
Allows user to create and name a backup of the current state of the investigapptor.
** Implemented ListInvestigatorCases command:
+
Allows user to view all cases allocated to the selected investigator.
** Implemented GUI for Investigator Details:
+
Created a html file to display the investigator details in a clear and more presentable format.
** Refactor the following command in order for investigator to integrate properly into Invesstigapptor.
+
*** AddInvestigatorCommand
*** EditInvestigatorCommand
*** DeleteInvestigatorCommand
** Implemented CrimeCaseBuilder class
+
CrimeCaseBuilder used in JUnit testing to help build CrimeCase
** Implemented InvestigatorBuilder class
+
InvestigatorBuilder used in JUnit testing to help build CrimeCase
* *Code contributed*: [https://github.com/CS2103JAN2018-F14-B3/main/blob/master/collated/functional/Marcus-cxc.md[Functional code]] [https://github.com/CS2103JAN2018-F14-B3/main/blob/master/collated/test/Marcus-cxc.md[Test code]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.2` (1 releases) on GitHub
** Documentation:
*** Did screenshots for several commands in the User Guide: https://github.com/CS2103JAN2018-F14-B3/main/pull/255[#255] https://github.com/CS2103JAN2018-F14-B3/main/pull/260[#260]
*** Did the navigating the interface section for the User Guide: https://github.com/CS2103JAN2018-F14-B3/main/pull/231[#231]
*** Filled in the future enhancement in the user doc: https://github.com/CS2103JAN2018-F14-B3/main/pull/244[#244]
*** Update the Design component for the Developer Guide https://github.com/CS2103JAN2018-F14-B3/main/pull/255[#255]
** Enhancements to existing features:
*** Update the sample data to reflect the new data type, investigator and cases: https://github.com/CS2103JAN2018-F14-B3/main/pull/264[#264]
* Community:
*** Reported bugs and suggestions for other teams (examples:
https://github.com/CS2103JAN2018-F11-B4/main/issues/120[1],
https://github.com/CS2103JAN2018-F11-B4/main/issues/132[2],
https://github.com/CS2103JAN2018-F11-B4/main/issues/128[3],
https://github.com/CS2103JAN2018-F11-B4/main/issues/104[4],
https://github.com/CS2103JAN2018-F11-B4/main/issues/110[5])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=addinv]
include::../UserGuide.adoc[tag=backup]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=addinvestigator]
include::../DeveloperGuide.adoc[tag=editinvestigator]
include::../DeveloperGuide.adoc[tag=listinvestigatorcase]
include::../DeveloperGuide.adoc[tag=backup]
