= Poh Kai Jun - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: INVESTIGAPPTOR

---

== Overview

Investigapptor is a desktop application used for investigators to manage cases as simple, straightforward and efficient as possible.
The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: Support to view cases efficiently
** *Features Implemented*:
*** Provide an overview of all the cases in a Calendar GUI (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/131[#131], https://github.com/CS2103JAN2018-F14-B3/main/pull/201[#201])
*** Command to display cases whose tags matches the keyword(s) provided by the user (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/100[#100])
*** Command to display cases whose status is close (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/223[#223])
*** Command to display cases whose status is open (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/223[#223])
*** Command to change the case's status from open to close (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/104[#104])
** What it does: This enhancement incorporates the abovementioned features to allow investigators to
view the cases they want in an efficient and user-friendly manner.
** Justification: Its essential for investigators to solve the crime cases within the shortest amount of time possible.
Hence, efficiency is key for the investigators. Bookkeeping is important as well
in order to manage and keep track of the cases - however, time spent on this area can be rather large
if there is no proper system to manage these information. +
+
By having this enhancement, it not only provides a better user experience for the investigators,
but more importantly, it reduces the time spent on bookkeeping work. With this enhancement,
investigators do not need to perform any manual work to display an overview of the cases in a nicely formatted
layout or having to search through a long list of data to find a particular set of cases.
Thus, this will improve the efficiency of the investigators as time will be spent on
significant events such as investigative work instead of bookkeeping tasks.

** Highlights: The Calendar GUI is not just a piece of static image on the interface. It interacts
with the various components in Investigapptor and will instantly reflect newly added cases, remove any deleted
cases or display only a certain set of cases when commands related to the cases are executed.

** Credits: The Calendar GUI was implemented with the external API, https://github.com/dlemmermann/CalendarFX[CalendarFX].

* *Minor enhancement*:
** Added functionality to provide different tag colours for different tag contents (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/137[#137])
** Added new command to display investigators whose tags matches the keyword(s) provided by the user (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/59[#59])
** Added new attribute `endDate` to CrimeCase class (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/104/commits/89f36467df0ae93ba1b5459685dc7db7d72918d7[#104])

* *Code contributed*: [https://github.com/CS2103JAN2018-F14-B3/main/blob/master/collated/functional/pkaijun.md[Functional code]] [https://github.com/CS2103JAN2018-F14-B3/main/tree/master/collated/test[Test code]]

* *Other contributions*:

** Project management:
*** Managed release `v1.5` (1 release) on GitHub
*** Referencing between `type.epic` `type.story` `type.task` `type.testing` to break down
the major enhancement into smaller tasks (Epic Issue https://github.com/CS2103JAN2018-F14-B3/main/issues/212[#212])

** Enhancements:
*** Implemented auto-update functionality for the Calendar to automatically reflect the current list of
cases shown on the panel
(Commit https://github.com/CS2103JAN2018-F14-B3/main/pull/237/commits/b4453b5a872a426632720086f2eea8904109a9ce[#237],
https://github.com/CS2103JAN2018-F14-B3/main/pull/223/commits/b3e3235967302ff3b47f20f732e055aef6062a4c[#223])

** Documentation:
*** Added screenshots to the User Guide to illustrate examples:
(PR https://github.com/CS2103JAN2018-F14-B3/main/pull/246[#246],
https://github.com/CS2103JAN2018-F14-B3/main/pull/225/[#225])

*** Updated Developer Guide's diagrams according to the components of the Investigapptor:
(PR https://github.com/CS2103JAN2018-F14-B3/main/pull/132/files[#132],
https://github.com/CS2103JAN2018-F14-B3/main/pull/232[#232],
https://github.com/CS2103JAN2018-F14-B3/main/pull/242[#242])

** Community:

*** Reported bugs and suggestions for other teams (examples:  https://github.com/CS2103JAN2018-T11-B4/main/issues/137[1],
https://github.com/CS2103JAN2018-T11-B4/main/issues/134[2],
https://github.com/CS2103JAN2018-T11-B4/main/issues/128[3],
https://github.com/CS2103JAN2018-T11-B4/main/issues/121[4],
https://github.com/CS2103JAN2018-T11-B4/main/issues/118[5],
https://github.com/CS2103JAN2018-T11-B4/main/issues/113[6],
https://github.com/CS2103JAN2018-T11-B4/main/issues/104[7],
https://github.com/CS2103JAN2018-T11-B4/main/issues/102[8])

** Tools:
*** Integrated a third party library (CalendarFX) to the project
(PR https://github.com/CS2103JAN2018-F14-B3/main/pull/131[#131],
https://github.com/CS2103JAN2018-F14-B3/main/pull/224[#224])

** Troubleshooting:
*** Fixed bugs from user testing (PR https://github.com/CS2103JAN2018-F14-B3/main/pull/204[#204])
*** Fixed bug from test case caused by the auto-update functionality (Commit https://github.com/CS2103JAN2018-F14-B3/main/pull/237/commits/4fd7aada969f97774a3a86afbad4267a2eca38ab[#237])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=findcasetags]

include::../UserGuide.adoc[tag=findinvtags]

include::../UserGuide.adoc[tag=findclosecases]

include::../UserGuide.adoc[tag=findopencases]

include::../UserGuide.adoc[tag=closecase]

include::../UserGuide.adoc[tag=calendarsection]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
